# Generated by Django 5.2.1 on 2025-10-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad_producida', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('material', 'Material Directo'), ('mano_obra', 'Mano de Obra Directa'), ('indirecto', 'Costo Indirecto de Fabricación')], max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='CostoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.producto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.recurso')),
            ],
            options={
                'verbose_name': 'Costo de Producción',
                'verbose_name_plural': 'Costos de Producción',
            },
        ),
    ]
